# Generated by Django 2.1.3 on 2018-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='cnt_fiodr',
            field=models.IntegerField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='extuser',
            name='total_square',
            field=models.IntegerField(blank=True, max_length=32),
        ),
    ]
