# Generated by Django 2.1.3 on 2018-11-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20181121_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='total_square',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='extuser',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedbackrecord',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
