# Generated by Django 2.1.3 on 2018-11-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20181121_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='cnt_fiodr',
            field=models.IntegerField(blank=True),
        ),
    ]
