# Generated by Django 2.1.3 on 2018-11-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20181121_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='cnt_fiodr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='extuser',
            name='total_square',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
