# Generated by Django 2.1.3 on 2018-11-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_auto_20181121_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricitymeters',
            old_name='value',
            new_name='valueDay',
        ),
        migrations.RenameField(
            model_name='electricitymeters',
            old_name='zone',
            new_name='valueNight',
        ),
        migrations.RenameField(
            model_name='watermeters',
            old_name='value',
            new_name='valueCold',
        ),
        migrations.AddField(
            model_name='watermeters',
            name='valueHot',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
