# Generated by Django 2.1.3 on 2018-11-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20181122_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricitymeters',
            old_name='valueDay',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='electricitymeters',
            old_name='valueNight',
            new_name='zone',
        ),
        migrations.RenameField(
            model_name='watermeters',
            old_name='valueCold',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='watermeters',
            name='valueHot',
        ),
    ]
