# Generated by Django 2.1.3 on 2018-11-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20181122_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('night', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('cold', models.IntegerField()),
                ('water', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Predictions',
        ),
    ]
