# Generated by Django 2.1.3 on 2018-11-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandPage', '0002_auto_20181111_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creationDate',
            field=models.DateTimeField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='partonymic',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=64),
        ),
    ]
