# Generated by Django 2.1.3 on 2018-11-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandPage', '0004_auto_20181111_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='DefaultUser',
        ),
    ]
