# Generated by Django 2.1.3 on 2018-11-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandPage', '0005_auto_20181111_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='login',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='mail',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='partonymic',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='surname',
            field=models.CharField(default='', max_length=128),
        ),
    ]
