# Generated by Django 2.1.3 on 2018-11-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandPage', '0006_auto_20181112_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultuser',
            old_name='partonymic',
            new_name='patronymic',
        ),
    ]
