# Generated by Django 2.1.3 on 2018-11-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandPage', '0007_auto_20181112_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='activationKey',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='activationType',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
