# Generated by Django 2.1.3 on 2018-11-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandPage', '0008_auto_20181112_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='activationDate',
            field=models.DateTimeField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='creationDate',
            field=models.DateTimeField(auto_now=True, max_length=64),
        ),
    ]
