# Generated by Django 2.1.3 on 2018-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandPage', '0009_auto_20181112_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='activationType',
            field=models.IntegerField(default=0),
        ),
    ]
