# Generated by Django 2.1.3 on 2018-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandPage', '0012_auto_20181115_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
