# Generated by Django 2.1.3 on 2018-11-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandPage', '0013_auto_20181115_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detailedNews',
            field=models.CharField(max_length=8128),
        ),
    ]
