# Generated by Django 2.1.3 on 2018-11-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandPage', '0015_subscriber'),
        ('LandPage', '0014_auto_20181118_0958'),
    ]

    operations = [
    ]
